config/routes.rb
Rails.application.routes.draw do
  resources :rsvps

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)

    respond_to do |format|
      if @rsvp.save
        UserNotifier.send_rsvp_email(@rsvp).deliver
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
   def rsvp_params
      params.require(:rsvp).permit(:name, :email, :coming, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sendgrid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :name %>
  <%= f.label :RSVP %>
  <%= f.text_field :coming %>
  <%= f.label :message %>
  <%= f.text_field :message %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing Rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rsvps</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <%= rsvp.name %>
        <td><%= link_to 'Show', rsvp %></td>
        <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
        <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New Rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>

app/views/user_notifier/send_rsvp_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @rsvp.name %></h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>